<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260108091943 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE workload (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, month INT NOT NULL, days NUMERIC(5, 2) NOT NULL, task_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1203AA7B8DB60186 ON workload (task_id)');
        $this->addSql('ALTER TABLE workload ADD CONSTRAINT FK_1203AA7B8DB60186 FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE workload DROP CONSTRAINT FK_1203AA7B8DB60186');
        $this->addSql('DROP TABLE workload');
    }
}
